### ISSUE TITLE
Network dependency vs. `depends on`

### ISSUE THREAD

**Issue by vdrover** [cascandaliato/docker-restarter#5]
I'm using [Gluetun](https://github.com/qdm12/gluetun) as my VPN client. My services that reply on Gluetun use `network mode` rather than `depends on`. Below I am showing a single service (Speedtest tracker) as an example.

Can I add docker-restarter to my stack in this scenario? Please advise any changes needed for me to test. Also, would this replace the need for autoheal?

```
  # Gluetun - VPN Client for Docker Containers and More
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - REDACTED
    devices:
      - /dev/net/tun
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
    environment:
      - TZ=$TZ
      - VPN_SERVICE_PROVIDER=REDACTED
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=REDACTED
      - SERVER_COUNTRIES=REDACTED

  # Speedtest tracker - simple way to monitor VPN via gluetun
  speedtest-tracker:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    container_name: speedtest-tracker
    network_mode: "service:gluetun"
    restart: always
    volumes:
      - '$DOCKERDIR/appdata/speedtest:/config'
     healthcheck:
      test: "curl -sf http://ipinfo.io/ip  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1

  # WatchTower - Automatic Docker Container Updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "0 30 12 * * *" # Everyday at 12:30
      DOCKER_API_VERSION: "1.40"

  # Autoheal
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```
